### ISSUE TITLE
请问sdk支持单片机平台吗?

### ISSUE THREAD

**Issue by upupsky** [huaweicloud/huaweicloud-iot-device-sdk-c#25]
有支持单片机的sdk吗?

**Comment by louiscrazy** [comment]
我已经收到您的邮件啦，谢谢

**Comment by jiaotanghengjiao** [comment]
该SDK不支持非Linux系统的，可以查看官网说明https://support.huaweicloud.com/sdkreference-iothub/iot_02_9980.html
