### ISSUE TITLE
如何获取平台下发文件上传临时 URL

### ISSUE THREAD

**Issue by Gipbear** [huaweicloud/huaweicloud-iot-device-sdk-c#30]

**Comment by Gipbear** [comment]
> _No description provided._

**Comment by longshijing** [comment]
1、华为云控制台登录账号，在设备接入->设备 -> 所有设备 -> 文件上传处，设置OBS桶。
2、查看该网站：https://support.huaweicloud.com/api-iothub/iot_06_v5_3033.html
