### ISSUE TITLE
远程 SSH 无法登录

### ISSUE THREAD

**Issue by chenglong-do** [huaweicloud/huaweicloud-iot-device-sdk-c#70]
硬件：树莓派 CM4
系统：Linux raspberrypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux

编译后成功运行，可以连上平台并上传数据，但是远程登录失败，设备端未见明确错误。

设备开启SSH登录通道成功！ Welcome to console.

等待设备开启ssh登录通道中...
终端已断开连接

**Comment by louiscrazy** [comment]
我已经收到您的邮件啦，谢谢

**Comment by jiaotanghengjiao** [comment]
使用新版是否还会出现该问题？可以咨询客服
