### ISSUE TITLE
Ubuntu22.04系统，SSH远程登录连接十几秒后自动断开

### ISSUE THREAD

**Issue by 63669733** [huaweicloud/huaweicloud-iot-device-sdk-c#74]
您好，如图所示，之前跟工程师一起发现了在ubuntu22.04系统中，SSH远程登录连接十几秒后自动断开的兼容性问题，工单工程师临时编译的版本可以解决连接自动断开的问题，但不能做为生产版本，期待尽快发布新版本解决此问题，谢谢
![image](https://github.com/huaweicloud/huaweicloud-iot-device-sdk-c/assets/12948697/75257af9-58a7-4ccd-9448-2217fbfd51c2)

![image](https://github.com/huaweicloud/huaweicloud-iot-device-sdk-c/assets/12948697/a4d48d3b-ff6c-4cd4-b341-f6d72035d701)

**Comment by jiaotanghengjiao** [comment]
你好，是否重复上报了设备状态。在SSH连接的情况下，请勿重复刷新设备状态，如果使用的是demo。可以把Test_ReportDeviceInfo() 拿出while循环即可。
