### ISSUE TITLE
编译错误SetDeviceConfigCallback

### ISSUE THREAD

**Issue by wangzc17** [huaweicloud/huaweicloud-iot-device-sdk-c#80]
IOTA_SetDeviceConfigCallback传入回调函数带的参数与SetDeviceConfigCallback的回调函数带的参数不一致

typedef int (*DEVICE_CONFIG_CALLBACK_HANDLER)(JSON *cfg);
void SetDeviceConfigCallback(DEVICE_CONFIG_CALLBACK_HANDLER callbackHandler);

typedef int (*PFN_DEVICE_CONFIG_CALLBACK_HANDLER)(JSON *cfg, char *description);
HW_API_FUNC HW_VOID IOTA_SetDeviceConfigCallback(PFN_DEVICE_CONFIG_CALLBACK_HANDLER callbackHandler);

**Comment by louiscrazy** [comment]
我已经收到您的邮件啦，谢谢

**Comment by jiaotanghengjiao** [comment]
修复了该问题 [gh pr checkout 82](https://github.com/huaweicloud/huaweicloud-iot-device-sdk-c/pull/82)
